server:
 port: 9999
 servlet:
  context-path: /

mybatis:
 mapper-locations: classpath:mapper/oracle/*/*.xml
 type-aliases-package: com.huasisoft.easyoffice.model
 configuration:
  cache-enabled: true
  lazy-loading-enabled: false
  multiple-result-sets-enabled: true 
  use-column-label: true
  use-generated-keys: false
  default-executor-type: SIMPLE
  default-statement-timeout: 25
  default-fetch-size: 100
  safe-row-bounds-enabled: false
  map-underscore-to-camel-case: true 
  local-cache-scope: SESSION
  jdbc-type-for-null: OTHER 
  lazy-load-trigger-methods: equals,clone,hashCode,toString,get
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
spring:
 profiles:
  active: dev2
   
   
 cache:  type: redis
  redis:
   key-prefix: flowCaches
   time-to-live: 3600
 
 freemarker:
  request-context-attribute: request

 jackson:
  time-zone: Asia/Shanghai
  serialization:
   write-dates-as-timestamps: true

 redis:
  timeout: 5000
  lettuce:
    pool:
     min-idle: 10
     max-idle: 10
     max-active: 20
     max-wait: 10000  
 
 session:
  timeout: 1800
  store-type: redis
  redis:
   flush-mode: on-save
   namespace: easyoffice
     
 aop:
  auto: true
  
# datasource:
#  driver-class-name: oracle.jdbc.OracleDriver
#  type: com.alibaba.druid.pool.DruidDataSource
   
# druid:
#  oracle: true
#  max-wait: 20000
#  time-between-eviction-runs-millis: 1200000
#  min-evictable-idle-time-millis: 1800000
#  max-evictable-idle-time-millis: 3600000
#  validation-query: SELECT 'x' FROM DUAL
#  default-read-only: true
#  test-while-idle: true
#  test-on-borrow: false
#  test-on-return: false
#  pool-prepared-statements: true
#  max-pool-prepared-statement-per-connection-size: 100
#  filters: stat
#  use-global-data-source-stat: true
#  stat-view-servlet:
#   enabled: true
#   login-username: monitor
#   login-password: huasi
#  web-stat-filter:
#   enabled: true
#   exclusions: "*.html,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid,/druid/*"
#  filter:
#   stat:
#    slow-sql-millis: 5000
#    merge-sql: true   
dubbo:
 application:
  name: flow-web
 registry:
   address: zookeeper://192.168.50.5:2181
 protocol:
   name: dubbo
   port: 6001
 provider:
   threads: 200
   version: 2.0.0
   timeout: 30000
 consumer:
   check: false
   version: 2.0.0
   timeout: 30000
 scan:
   base-packages: com.huasisoft.flow

scheduleExector:
 pool:
  size: 6
threadPool:
 min: 5
 max: 10
 queueSize: 20
 keepAlive: 3600
checkUserFilter:
 ignorePattern: /services/*
 
