server:
 port: 8091
 servlet:
  context-path: /flow
  path: /
 connection-timeout: 5000
 tomcat:
  max-threads: 80
  min-spare-threads: 10  #压测可以配200
  uri-encoding: UTF-8
  accept-count: 80      #队列长度
  max-connections: 100

# flowable 配置
flowable:
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false
  database-schema-update: false
  modeler:
    app:
      dataSourcePrefix: FLOW.
spring:
 redis:
  host: 192.168.50.5
  port: 6379
  #password: 123456
  #cluster:
  # nodes: 10.0.0.35:20011,10.0.0.35:20012,10.0.0.35:20013,10.0.0.35:20014,10.0.0.35:20015,10.0.0.35:20016
  # max-redirects: 3
  lettuce:
   pool:
    min-idle: 10
    max-idle: 10
    max-active: 20
 session:
  timeout: 1800
 servlet:
  multipart:
   enabled: true
   max-file-size: 200MB  #单个文件的最大上限
   max-request-size: 500MB #单个请求的文件总大小上限
 datasource:
  url: jdbc:dm://192.168.50.30:5236/FLOW
  username: FLOW
  password: FLOWFLOWFLOW
  driver-class-name: dm.jdbc.driver.DmDriver
  druid:
   initial-size: 10
   min-idle: 10
   max-active: 25
   stat-view-servlet:
    enabled: false
   web-stat-filter:
    enabled: false
   aop-patterns: com.huasisoft.flow.*.serviceImpl.*
   filters:
 data:
  mongodb:
   uri: mongodb://192.168.50.5:27017/gm_easyoffice?connectTimeoutMS=10000;socketTimeoutMS=10000;waitQueueTimeoutMS=10000;minPoolSize=20;maxPoolSize=280;maxIdleTimeMS=3600000;readPreference=primaryPreferred;w=majority;wtimeoutMS=10000;
   #uri: mongodb://admin_H5:huasiH5@10.0.0.198:27017/h1?connectTimeoutMS=10000;socketTimeoutMS=0;minPoolSize=20

#authMechanism=SCRAM-SHA-1;
#retryWrites=true;
# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/huasisoft/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  configuration-properties:
    dbSchema: FLOW.
  mapper-locations: classpath:/mapper/dm/**/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.huasisoft.flow.**.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: NONE
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: DM DBMS
dubbo:
 registry:
  address: zookeeper://192.168.50.5:2181
 protocol:
  port: 6001


defaultRelogUrl: http://192.168.50.5:7066/sso?service=http://192.168.50.218:8091/flow

#filter配置

singleSignOutFilter:
 casServerUrlPrefix: http://192.168.50.5:7066/sso

authenticationFilter:
 casServerLoginUrl: http://192.168.50.5:7066/sso/login
 serverName: http://192.168.50.218:8091
 ignorePattern: (/services/)|(/static/)

servicesAuthorityFilter:
 urlPatterns: /services/*


#是否开启service服务注册
isServiceRegistered: false

#顶级资源ID
rootResourceID: 9c0b4593-cae0-4129-a064-34d6fc692e81

#顶级按钮资源ID
buttonReourceID: cae918ad-eb46-4af7-80b8-1103730c15e9

rootOrgID: '{00000000-0000-0000-0000-000000000000}'

